function   [dFE,sx,v]= VB_compute(NstateFactors,      ...
                                  iVB,                ...
                                  TimeHorizon,        ...
                                  pstatesTimePols,    ...
                                  Vset,               ...
                                  tau,                ...
                                  R,                  ...
                                  dF,                 ...
                                  qL,                 ...
                                  Dmatrix,            ...
                                  iTH,                ...
                                  BmatS)
% function [dFE,sx,v]= VB_compute(NstateFactors,      ...
%                                 iVB,                ...
%                                 TimeHorizon,        ...
%                                 pstatesTimePols,    ...
%                                 Vset,               ...
%                                 tau,                ...
%                                 R,                  ...
%                                 dF,                 ...
%                                 qL,                 ...
%                                 Dmatrix,            ...
%                                 iTH,                ...
%                                 BmatS)
tBmatS=zeros(size(BmatS));
for iaction = 1:size(BmatS,3)      
    % transposed normalize parameters B
    %--------------------------------------------------------------            
    tBmatS(:,:,iaction)    = spm_norm(BmatS(:,:,iaction)'); 
end      
sx = pstatesTimePols(:,iTH);

% hidden states for this time and policy
%----------------------------------------------
v = 0;
% evaluate free energy and gradients (v = dFdx)
%----------------------------------------------
if dF > exp(-8) || iVB > 4     
    % entropy
    %------------------------------------------
    qx  = spm_log(sx);
    % emprical priors (forward messages)
    %------------------------------------------
    if iTH < 2
        px = spm_log(Dmatrix);
        v  = v + px + qL - qx;
    else
        px = spm_log(BmatS(:,:,Vset(iTH - 1))*pstatesTimePols(:,iTH - 1));   
        v  = v + px + qL - qx;
    end    
    % empirical priors (backward messages)
    %------------------------------------------
    if iTH < R
        px = spm_log(tBmatS(:,:,Vset(iTH))*pstatesTimePols(:,iTH + 1));    
        v  = v + px + qL - qx;
    end
    % (negative) free energy
    %------------------------------------------
    if iTH == 1 || iTH == TimeHorizon
        dFE = sx'*0.5*v;
    else
        dFE = sx'*(0.5*v - (NstateFactors-1)*qL/NstateFactors);
    end    
    % update
    %------------------------------------------
    v    = v - mean(v);
    sx   = spm_softmax(qx + v/tau);    
else
    dFE = 0;
end