function   [N_LINE,LINE_VEC,iw_end]=PLOT_LineCount(WORDNUMBER,NUMBW_LINE)
% function [N_LINE,LINE_VEC,iw_end]=PLOT_LineCount(WORDNUMBER,NUMBW_LINE)

Q_LINE = floor(WORDNUMBER/NUMBW_LINE);
N_LINE = Q_LINE+1;
LINE_VEC=NUMBW_LINE*ones(1,N_LINE-1);
iw_end=NUMBW_LINE:NUMBW_LINE:(N_LINE-1)*NUMBW_LINE;
if rem(WORDNUMBER,NUMBW_LINE)>0
    LINE_VEC(end+1)   = WORDNUMBER-NUMBW_LINE*Q_LINE;
    iw_end(end+1)     = WORDNUMBER;
end
